config/routes.rb
Rails.application.routes.draw do
  authenticate :user, ->(user) { user.admin? } do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end
  devise_for :users
  root to: "pages#home"
  resources :reviews, only: [:index, :new, :create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "cv", to: "pages#cv"
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user


  validates :content, presence: { message: "You need to fill in content" }
  validates :rating, presence: { message: "You need to provide a rating between 1 and 5" },
            numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  has_one :review, dependent: :destroy
  validates :first_name, presence: true
  validates :last_name, presence: true
  before_validation :downcase_email

  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: URI::MailTo::EMAIL_REGEXP, message: "must be a valid email address" }

  def admin?
    self.admin
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable

  private

  def downcase_email
    self.email = email.to_s.downcase.strip
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  def after_sign_up_path_for(resource)
    new_review_path
  end

  def after_sign_in_path_for(resource)
    if resource.sign_in_count == 1
      new_review_path
    else
      super
    end
  end

  def not_found
    raise ActionController::RoutingError.new("Page not found")
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :cv ]

  def home
  end

  def cv
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index ]
  before_action :authenticate_user_or_redirect!, only: [:new, :create]

  def index
    @reviews = Review.order(created_at: :desc)
  end
  def new
    @review = Review.new
  end
  
  def create
    @review = Review.new(review_params)
    @review.user = current_user

    if @review.save
      redirect_to reviews_path, notice: "Review submitted successfully!"
    else
      flash.now[:alert] = "Upss something went wrong.Please try once more, dont be lazy 😂!"
      render :new
    end
  end

  private

  def authenticate_user_or_redirect!
    unless user_signed_in?
      redirect_to new_user_registration_path, alert: "Please sign up to leave a review."
    end
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Klevion Xhoxhaj | Portfolio </title>
    <meta name="description" content="Discover my portfolio website, crafted using Ruby on Rails, HTML, SCSS, and StimulusJS. Built to showcase my web development expertise, it features a review system where visitors can sign in, share feedback, and experience dynamic, user-friendly design.">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="turbo-visit-control" content="disable">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://ga.jspm.io/npm:star-rating.js@4.3.0/dist/star-rating.css">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600;700&family=Montserrat:wght@400;500;700&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/pages/cv.html.erb
<section class="cv-banner">
  <%= render "shared/navbar" %>
  <div id="cv-index" class="container" data-controller="swap-view">
    <div class="about-links">
      <a id="profile-button" class="about-button active" data-action="swap-view#displayProfile" data-swap-view-target="profileLink">Profile</a>
      <a id="experience-button" class="about-button" data-action="swap-view#displayProjects" data-swap-view-target="projectsLink">Projects&Experience</a>
      <a id="education-button" class="about-button" data-action="swap-view#displayEducation" data-swap-view-target="educationLink">Education</a>
    </div>
    <div id="about-profile" class="about-contents" data-menu-target="contents" data-swap-view-target="profile">
      <h3>🧔🏻‍♂️ About me</h3>
      <section class="orange-strip">
      </section>
      <p>
        Fullstack Developer with a passion for creating innovative, user-focused solutions. I completed an intensive 9-week Fullstack Development program at Le Wagon in September 2023, where I gained hands-on experience building a project aimed at enhancing the workout experience for sports enthusiasts. This training provided me with a strong foundation in development, alongside a collaborative and problem-solving mindset. I am eager to contribute to dynamic teams, leveraging my skills to design and deliver impactful solutions that improve user experiences and drive innovation.
      </p>
      <h3>🥷 Skills</h3>
      <section class="orange-strip">
      </section>
      <p>
        <a href="https://rubyonrails.org" target="_blank" rel="noreferrer"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/rails/rails-original-wordmark.svg" alt="rails" width="50" height="50"/>
        </a>
        <a href="https://www.w3.org/html/" target="_blank" rel="noreferrer"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original-wordmark.svg" alt="html5" width="50" height="50"/>
        </a>
        <a href="https://www.w3schools.com/css/" target="_blank" rel="noreferrer"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/css3/css3-original-wordmark.svg" alt="css3" width="50" height="50"/>
        </a>
        <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript" target="_blank" rel="noreferrer"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/javascript/javascript-original.svg" alt="javascript" width="50" height="50"/>
        </a>
        <a href="https://www.ruby-lang.org/en/" target="_blank" rel="noreferrer"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/ruby/ruby-original.svg" alt="ruby" width="50" height="50"/>
        </a>
        <a href="https://www.postgresql.org" target="_blank" rel="noreferrer"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/postgresql/postgresql-original-wordmark.svg" alt="postgresql" width="50" height="50"/>
        </a>
        <a href="https://react.dev/" target="_blank" rel="noreferrer"><img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/react/react-original-wordmark.svg" alt="React" width="50" height="50" />
        </a>
        <a href="https://www.typescriptlang.org/" target="_blank" rel="noreferrer"><img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/typescript/typescript-original.svg" alt="TypeScript" width="50" height="50" />
        </a>
        <a href="https://sass-lang.com/" target="_blank" rel="noreferrer"><img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/sass/sass-original.svg" alt="SASS" width="50" height="50" />
        </a>
      </p>
      <h3>🛠️ Tools</h3>
      <section class="orange-strip">
      </section>
      <p>
        <a href="https://getbootstrap.com" target="_blank" rel="noreferrer"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/bootstrap/bootstrap-plain-wordmark.svg" alt="bootstrap" width="50" height="50"/>
        </a>
        <a href="https://www.figma.com/" target="_blank" rel="noreferrer"> <img src="https://www.vectorlogo.zone/logos/figma/figma-icon.svg" alt="figma" width="50" height="50"/>
        </a>
        <a href="https://git-scm.com/" target="_blank" rel="noreferrer"> <img src="https://www.vectorlogo.zone/logos/git-scm/git-scm-icon.svg" alt="git" width="50" height="50"/>
        </a>
        <a href="https://heroku.com" target="_blank" rel="noreferrer"> <img src="https://www.vectorlogo.zone/logos/heroku/heroku-icon.svg" alt="heroku" width="50" height="50"/>
        </a>
        <a href="https://code.visualstudio.com/" target="_blank" rel="noreferrer"><img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/vscode/vscode-original.svg" alt="VS Code" width="50" height="50" />
        </a>
      </p>
    </div>
    <div id="about-projects-experience" class="about-contents d-none" data-menu-target="contents" data-swap-view-target="projects">
      <h3>🖥️  Projects</h3>
      <section class="orange-strip mb-0">
      </section>
      <p>
        <b class="bold-text">
        React Shopping List  <%= link_to("https://kxhoxhaj.github.io/shopping-list/", class: "social-link") do %>
        <i class="fa-solid fa-globe"></i>
      <% end %>
        </b><br>
        In case you need to do your shopping today feel free to use this simple digital list to simplify your shopping. "By the way is free, you are welcome 🤪"
        <br>
        Key Features:
        <br> • User-Friendly Interface
        <br> • CRUD Functionality (You can Add, Check and Delete a item from your shopping list)
        <br> • Search Feature (In case your list gets too long)
        <br>
        <b class="bold-text">
        PiperoCare Medical Center  <%= link_to("https://www.piperocare.org/", class: "social-link") do %>
        <i class="fa-solid fa-globe"></i>
      <% end %>
        </b><br>
        Developed a user-friendly website for PiperCare Medical Center, enhancing its
        online visibility and streamlining internal processes. The site features a
        comprehensive service catalog, CRUD functionality for efficient service
        management, and a prospective appointment booking system to improve client
        accessibility.
        <br>
        Key Features:
        <br> • User-Friendly Interface
        <br> • Service Catalog
        <br> • CRUD Functionality
        <br> • Admin Feature
        <br> • Prospective Appointment Booking (Planned)
        <br>
        <b class="bold-text">
        Harry Potter Cluedo Helper <%= link_to("https://kxhoxhaj.github.io/cluedo-helper/", class: "social-link") do %>
        <i class="fa-solid fa-globe"></i>
      <% end %>
        </b><br>
        Designed and implemented a personalized web application to streamline the
        Cluedo board game experience. The project addressed the inconvenience of
        running out of helping papers by providing a digital platform for note-taking
        during gameplay. The web app is tailored for the Harry Potter Cluedo version and
        offers a user-friendly interface for a more enjoyable gaming session with friends.
        Built with HTML, SASS, and Bootstrap.
        <br>
        <b class="bold-text">
        Shape Sync
        </b><br>
        Collaborated in a team of five to develop a dynamic web application aimed at
        assisting gym members in tracking their workouts and achieving fitness goals.
        Utilized Ruby on Rails, integrated APIs, and implemented Pundit for enhanced
        authorization. The project's future roadmap includes integrating AI capabilities to
        generate personalized workout programs based on individual user goals,
        enhancing the overall fitness experience.
        <br>
        <b class="bold-text">
        Earth BNB
        </b><br>
        Contributed to a team of five in the development of a website facilitating the
        rental of private islands or enabling island owners to list their properties for rent.
        Implemented Ruby on Rails for robust backend functionality, leveraged Geocoder
        for geospatial data, and integrated Mapbox for interactive mapping features. The
        collaborative effort aimed to create a user-friendly platform connecting island
        enthusiasts with unique rental opportunities.
      </p>
      <h3>💼 Experience</h3>
      <section class="orange-strip">
      </section>
      <p>
      <b class="bold-text">Junior Web Developer, Eder Studio</b>
      <br>
      02/2024 – 09/2024 | Tirana, Albania<br>
      • Contributed to the development of web applications, enhancing user experience and functionality for small businesses at Eder Studio.
      <br>
      • Assisted in the design and implementation of websites, ensuring responsive design and cross-browser compatibility.
      <br>
      • Collaborated with a team of developers to troubleshoot and resolve issues, improving overall project efficiency.
      <br>
      • Participated in client meetings to gather requirements and provide updates on project progress, fostering strong client relationships.
      <br>
      • Conducted testing and debugging of web applications, ensuring high-quality deliverables before launch.
      <br>
        <b class="bold-text">Project Engineer, Site Supervisor, Mechanical Engineer,
      Vali Group, Vali Engineering</b>
      <br>

      05/2019 – 09/2022 | London, England<br>
      • Worked on Building Maintenance Projects solving cold and hot water supply
      system problems for commercial and residential buildings allover London
      which enhanced my problem solving skills. To mention a few of the most
      known: "The Tower of London"
      "The Guardian" and "BNP Paribas"
      ,<br>
      • Oversaw the design and drawing of mechanical systems within buildings and
      spotted potential issues (mechanical electrical and/or plumbing) in the
      building<br>
      • Removed existing defective components and reinstated system with new
      components.<br>
      • Tested updated system by running full building test pressure, tested electrical
      components functionality, ensured system being full operational.
      </p>
    </div>
    <div id="about-education" class="about-contents d-none" data-menu-target="contents" data-swap-view-target="education">
      <h3>📙  Education</h3>
      <section class="orange-strip">
      </section>
      <p>
        <b class="bold-text">Web Development, Le Wagon</b><br>
        2023 | Berlin, Germany<br>
        • Completed a full-time coding bootcamp.<br>
        • Learned and applied Ruby on Rails, HTML, CSS, Bootstrap, JavaScript, SQL, Git,
        GitHub and Heroku.<br>
        • Designed, implemented, and launched a clone of AirBnB called Earth BNB to
        production.<br>
        • Pitched the idea for a web app, ShapeSync, and successfully completed the
        project in a team of five in just two weeks.
        <br>
        <b class="bold-text">Introduction to Web Development, Coursera</b><br>
        2023 | Berlin, Germany<br>
        • Create and styled a webpage with HTML and CSS.<br>
        • Learned the benefits of working with UI frameworks.<br>
        <b class="bold-text">Polytechnic University of Tirana</b><br>
        2013 – 2017 | Tirana, Albania<br>
        • Bachelor of Hydrotechnical Engineering.
      </p>
      <h3>🌐 Languages</h3>
      <section class="orange-strip">
      </section>
      <section id="languages">
        <ul class="languages">
          <li>
            <p class="flags">
              🇦🇱
            </p>
            <section class="stars">
              <% 5.times do %>
                <%= image_tag 'icons/star.svg', class: "svg-star" %>
              <% end %>
            </section class="stars">
          </li>
          <li>
            <p class="flags">
              🏴󠁧󠁢󠁥󠁮󠁧󠁿
            </p>
            <section class="stars">
              <% 4.times do %>
                <%= image_tag 'icons/star.svg', class: "svg-star" %>
              <% end %>
              <%= image_tag 'icons/emptystar.svg', class: "svg-star" %>
            </section class="stars">
          </li>
          <li>
            <p class="flags">
              🇮🇹
            </p>
            <section class="stars">
              <% 4.times do %>
                <%= image_tag 'icons/star.svg', class: "svg-star" %>
              <% end %>
              <%= image_tag 'icons/emptystar.svg', class: "svg-star" %>
            </section class="stars">
          </li>
          <li>
            <p class="flags">
              🇹🇷
            </p>
            <section class="stars">
              <% 3.times do %>
                <%= image_tag 'icons/star.svg', class: "svg-star" %>
              <% end %>
              <% 2.times do %>
                <%= image_tag 'icons/emptystar.svg', class: "svg-star" %>
              <% end %>
            </section class="stars">
          </li>
          <li>
            <p class="flags">
              🇩🇪
            </p>
            <section class="stars">
              <%= image_tag 'icons/star.svg', class: "svg-star" %>
              <% 4.times do %>
                <%= image_tag 'icons/emptystar.svg', class: "svg-star" %>
              <% end %>
            </section class="stars">
          </li>
        </ul>
        <section class="languages-img"></section>
      </section>
    </div>
  </div>
</section>

app/views/pages/home.html.erb
<div id="home">
  <%= render "shared/navbar" %>
  <section id="profile">
    <h1>Klevion Xhoxhaj</h1>
    <div class="profile-picture"></div>
    <p>Full-Stack Web Developer</p>
    <p class="contact-text">Contact me:</p>
    <section class="social-links">
      <%= link_to("mailto:klevionxhoxhaj@gmail.com", class: "social-link") do %>
        <i class="fa-solid fa-envelope"></i>
      <% end %>
      <%= link_to("https://www.instagram.com/klevion_xhoxhaj/", class:"social-link",  target: "_blank") do %>
        <i class="fa-brands fa-instagram"></i>
      <% end %>
      <%= link_to("https://github.com/kxhoxhaj", class:"social-link",  target: "_blank") do %>
        <i class="fa-brands fa-github"></i>
      <% end %>
      <%= link_to("https://www.linkedin.com/in/k-xh/", class:"social-link",  target: "_blank") do %>
        <i class="fa-brands fa-linkedin-in"></i>
      <% end %>
    </section>
  </section>
</div>

app/views/reviews/index.html.erb
<section class="review-banner">
  <%= render "shared/navbar" %>
  <div id="review-index" class="container">
    <% if user_signed_in? && !current_user.review || !user_signed_in? %>
      <%= link_to "👉 Review this website", new_review_path, class: "flash-link", id: "new-review" %>
    <% end %>
    <h1 class="main-header">Reviews</h1>
    <% if @reviews.any? %>
      <section class="star-display">
        <section class="ratings-total">
          <h2>
            Total: <%= @reviews.length %>
          </h2>
        </section>
        <section class="stars">
          <% sum = @reviews.sum { |review| review.rating || 0 } %>
          <% average = @reviews.any? ? sum / @reviews.length.to_f : 0 %>
          <% full_stars = average.floor %>
          <% half_star = (average % 1) >= 0.1 %>
          <% empty_stars = [5 - full_stars - (half_star ? 1 : 0), 0].max %>

          <h2><%= average.round(1) %></h2>
          <% full_stars.times do %>
            <%= image_tag 'icons/star.svg', class: "svg-star" %>
          <% end %>

          <% if half_star %>
            <%= image_tag 'icons/halfstar.svg', class: "svg-star" %>
          <% end %>

          <% empty_stars.times do %>
            <%= image_tag 'icons/emptystar.svg', class: "svg-star" %>
          <% end %>
        </section>
      </section>

      <div class="review-div d-flex justify-content-center">
        <ul class="reviews-list">
          <% @reviews.each do |review| %>
            <li class="review-card">
              <section class="review-header">
                <div class="user-initials">
                  <p><%= review.user&.first_name&.first&.upcase %><%= review.user&.last_name&.first&.upcase %></p>
                </div>
                <p class="review-content">
                  <%= review.content.presence || "No review content provided." %>
                </p>
              </section>
              <p class="rating-star">
                <% if review.rating < 5 %>
                  <% review.rating.times do %>
                    <%= image_tag 'icons/star.svg', class: "svg-star" %>
                  <% end %>
                  <% (5 - review.rating).times do %>
                    <%= image_tag 'icons/emptystar.svg', class: "svg-star" %>
                  <% end %>
                <% else %>
                  <% review.rating.times do %>
                    <%= image_tag 'icons/star.svg', class: "svg-star" %>
                  <% end %>
                <% end %>
              </p>
            </li>
          <% end %>
        </ul>
      <% else %>
        <p class="font-size">
          There are no reviews yet...! Be the first to leave one.
        </p>
        <% if !user_signed_in? %>
          <%= link_to "👉 Review this website", new_user_registration_path, class: "flash-link", id: "new-review" %>
        <% end %>
      <% end %>
    </div>
  </div>
</section>

app/views/reviews/new.html.erb
<section class="review-banner">
  <div id="review-new" class="container">
    <% if current_user.review %>
      <section class="existing-review">
        <p>Your review has already been posted 👍🏻! Thank you very much 🙏🏻, it really helps me a lot!</p>
        <%= link_to "Reviews", reviews_path, class: "submit-button", data: { action: "toggle-active-class#toggleReviews", toggle_active_class_target: "reviews", turbo: "false" } %>
      </section>
    <% else %>
      <section class="info-message">
        <p>👋 This review section is for you to leave a review and comment on this website for training purposes. Any advice on what to improve is welcome! Thank you in advance and 🍻 cheers!</p>
        <p>⭐ <b>Note:</b> Please be kind 😈!</p>
        <%= link_to "Reviews", reviews_path , class: "submit-button" %>
      </section>
      <section class="login-form">
        <%= simple_form_for @review do |f| %>
          <% if @review.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>
              <ul>
                <% @review.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="form-inputs">
            <%= f.input :content,
                        required: true,
                        input_html: { class: "transparent" },
                        placeholder: "Write your comment here..." %>
            <%= f.input :rating,
                        collection: (1..5).to_a,
                        label: "Rate your experience",
                        required: true,
                        include_blank: "Select a rating",
                        input_html: { class: "stars", data: { controller: "star-rating" } } %>
          </div>
          <div class="form-actions">
            <%= f.submit "Send your review", class: "submit-button" %>
          </div>
        <% end %>
      </section>
    <% end %>
  </div>
</section>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="flash flash-success alert alert-dismissible fade show" style="color: white;" role="alert">
    <span><strong>Yay!</strong> <%= notice %></span>
    <a data-bs-dismiss="alert" aria-label="Close">
      <i class="fas fa-times" style="color: red;"></i>
    </a>
  </div>
<% end %>
<% if alert %>
  <div class="flash flash-danger alert alert-dismissible fade show" style="color: white;" role="alert">
    <span><strong>Oops!</strong> 😱 <%= alert %></span>
    <a data-bs-dismiss="alert" aria-label="Close">
      <i class="fas fa-times" style="color: red;"></i>
    </a>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <div class="navbar-expand-sm navbar-light navbar-lewagon">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fa-solid fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent" data-controller="toggle-active-class">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link active" , data: { action: "toggle-active-class#toggleHome", toggle_active_class_target: "home", turbo: "false" }%>
          </li>
          <li class="nav-item">
            <%= link_to "About", cv_path, class: "nav-link" , data: { action: "toggle-active-class#toggleAbout", toggle_active_class_target: "about", turbo: "false" }%>
          </li>
          <li class="nav-item">
            <%= link_to "Reviews", reviews_path , class: "nav-link", data: { action:"toggle-active-class#toggleReviews", toggle_active_class_target: "reviews", turbo: "false" }%>
          </li>
          <% if user_signed_in? && current_user.admin? %>
            <li class="nav-item">
              <%= link_to "Admin",  rails_admin_path, class: "nav-link" %>
            </li>
          <% end %>
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Sign Up", new_user_registration_path, class: "nav-link"%>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

</div>